### ISSUE TITLE
Unnecessary Optional in expand method

### ISSUE THREAD

**Issue by fmalchemist92** [plinss/uri-template#1]
URITemplate.expand(**kwargs) -> Optional[str]
URITemplate.partial(**kwargs) -> Optional[URITemplate]
Is it really necessary for the function to return an optional value? After all, template validation takes place in the class constructor and the method always returns a string (in any case, I could not achieve otherwise)

**Comment by plinss** [comment]
The `None` result happens when a variable with a prefix modifier is expanded with a composite value (list or dict). This is forbidden per spec (see https://tools.ietf.org/html/rfc6570#section-2.4.1  "Prefix modifiers are not applicable to variables that have composite values") and can only be detected at expansion time.

The tests in https://github.com/uri-templates/uritemplate-test/blob/master/negative-tests.json indicate that this situation should fail (though the spec text is a bit ambiguous and could be interpreted to mean just ignore the prefix modifier).

The options are to return `None` or raise an exception (or ignore the prefix modifier, but given that the tests were written by the spec authors, I'm inclined to trust the tests where the spec is vague).

There's an `ExpansionFailed` exception class used internally (when caught causes the `None` return), it would be simple to just stop catching the exception, and/or have variations on the expand/partial methods that raise exceptions instead of returning `None`. Any preference, or suggestions for the alternate method names?

**Comment by fmalchemist92** [comment]
In this case, it would be more convenient if the `expand` method throws an exception out. Otherwise, the error is hidden from the user. And you can notice it only by indirect signs, comparing the return value with None. Therefore, I think the method should throw an exception in any case. But a free function can be made like 
`def expand(template: str, **kwargs, default_url: Optional[str] = None) -> Optional[str]:`
