### ISSUE TITLE
1.2.0: incorrect version in setup.py

### ISSUE THREAD

**Issue by kloczek** [plinss/uri-template#5]
https://github.com/plinss/uri_template/blob/ae070b1716c853fbc5a3c879e6ef1d1cfb2c9533/setup.py#L10

**Comment by plinss** [comment]
As indicated in the comment, the version gets replaced by the CI jobs during package deployment

**Comment by kloczek** [comment]
Issue is that thi sproduces wrong output on ue git resources.
Is it any problem with put actual verion in setup.py  before tagg repo like it is done in amny other git repos? 🤔 (just asking)

**Comment by plinss** [comment]
Because that either needs to be done by hand or by the CI system. Doing it by hand is error prone. Having the CI system make commits is generally a bad practice and results in unsigned commits or requires key management and possible leakage. Either way, it causes unnecessary commits and diffs.

The version number is specified by the git tag, not by the code. Putting the version in the code is an anti-pattern.

Modern Python packaging using pyproject.toml and setuptools-scm avoid having the version in the config entirely. At some point, I'll be updating this repo to use that as I do in my other projects.

**Comment by kloczek** [comment]
Many projects have special CI pipeline for releases which is used to updates version -> commit version change -> tags repo. Such thing reduces possibility to make such mistakes to null.
I have now packaged as rpm packages over 1.0k python modules and none is using approach like your.
Issue is that to have guarantee that I would be able to use any commit added to VCS after release I'm using VCS generated tar balls. Such situation is not rare case:
```console
[tkloczko@pers-jacek SPECS]$ grep Source:.*VCS python-* |wc -l; grep Patch:.*VCS python-* |wc -l
1029
518
```

**Comment by plinss** [comment]
And as I said, using CI causes unnecessary commits and diffs. [Just because a lot of people do it, doesn't mean it's good](https://en.wikipedia.org/wiki/Anti-pattern).

Furthermore, packaging individual Python modules as rpm packages is also an anti-pattern, so you might want to reconsider what you're doing. Having packages installed on a system managed by two different package managers causes all sorts of headaches. Python has a package management system, use it.

Packaging a Python application as an rpm is fine, but then all the dependency modules should be bundled in the application package and installed in a virtual environment, not polluting the global package space. You're asking for dependency nightmares otherwise.

I'm not in favor of rpm packages for my Python modules, but If you really want to build an rpm of my module, you're free to do so, just run `tools/set_version` before building the package. When it gets switched to setuptools-scm the set_version script will be removed and the normal build process will do the same, so make any automation skip set_version if the file no longer exists and you'll be fine.

You should also not be using simple tarballs of repositories for packaged Python modules. Python has a sanctioned build system, use it.

**Comment by kloczek** [comment]
> Just because a lot of people do it, doesn't mean it's good

As long as it is not creating unexpected issues it is fine.
Using analogies instead straight proves in most of the cases points on incorrecto conclutions .. especially in cases when it is not necessary to use analogies becausethere is possible to finf available facts 😋

**Comment by plinss** [comment]
> As long as it is not creating unexpected issues it is fine.

And as I already said, it causes issues. Which you have not addressed.

> Using analogies instead straight proves

I'm not using analogies, I'm using the definition of an anti-pattern.

So bottom line here, you're asking me to do work, to change an existing system that works, into one that has issues I don't want, to support you doing something with my code that I don't support. You're providing no justification other than 'other people do it'. You're not addressing my concerns. And you're making specious arguments and insulting me. Good plan.

Please take a long hard look at your behavior and hopefully make better decisions in the future.
